In [123]:
import pandas as pd
import numpy as np


In [124]:
data = pd.read_excel('iris.xls')

In [125]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [126]:
x = data.drop('Classification', axis = 1)
y = data['Classification']

In [127]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42, test_size = 0.4)

In [128]:
x_test.head()

SL   SW   PL   PW
73   6.1  2.8  4.7  1.2
18   5.7  3.8  1.7  0.3
118  7.7  2.6  6.9  2.3
78   6.0  2.9  4.5  1.5
76   6.8  2.8  4.8  1.4

In [129]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [130]:
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, f1_score
from sklearn.metrics import classification_report
def model_performance(y_true, x_test, model):
  y_pred = model.predict(x_test)
  print(classification_report(y_true, y_pred))
  print('accuracy' , accuracy_score(y_true, y_pred))
  print('precision_score', precision_score(y_true, y_pred, average='micro'))
  print('f1-score', f1_score(y_true,y_pred , average='micro'))
  print('confussion matrix')
  print(confusion_matrix(y_true,y_pred))

In [131]:
x_test.shape

(60, 4)

In [132]:
# MODEL
from sklearn.neighbors import KNeighborsClassifier
K_model = KNeighborsClassifier(n_neighbors=3)
K_model.fit(x_train, y_train)
model_performance(y_test, x_test, K_model)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        23
Iris-versicolor       1.00      0.95      0.97        19
 Iris-virginica       0.95      1.00      0.97        18

       accuracy                           0.98        60
      macro avg       0.98      0.98      0.98        60
   weighted avg       0.98      0.98      0.98        60

accuracy 0.9833333333333333
precision_score 0.9833333333333333
f1-score 0.9833333333333333
confussion matrix
[[23  0  0]
 [ 0 18  1]
 [ 0  0 18]]


In [133]:
#  MODEL CREATED AND SAVING THE MODEL OBJECT
import pickle
with open('model.pkl', 'wb') as fp:
    pickle.dump(K_model, fp)

In [136]:
x_test[:5]

array([[ 0.26147279, -0.72939641,  0.58284971,  0.08597877],
       [-0.21393228,  1.4479063 , -1.0487669 , -1.07473463],
       [ 2.16309308, -1.16485695,  1.77936855,  1.50462848],
       [ 0.14262152, -0.51166614,  0.47407527,  0.47288324],
       [ 1.09343166, -0.72939641,  0.63723693,  0.34391508]])

In [134]:
y_test.head()

73     Iris-versicolor
18         Iris-setosa
118     Iris-virginica
78     Iris-versicolor
76     Iris-versicolor
Name: Classification, dtype: object

In [137]:
data.iloc[73]

SL                            6.1
SW                            2.8
PL                            4.7
PW                            1.2
Classification    Iris-versicolor
Name: 73, dtype: object

In [139]:
data.iloc[118]

SL                           7.7
SW                           2.6
PL                           6.9
PW                           2.3
Classification    Iris-virginica
Name: 118, dtype: object