In [1]:
import pandas as pd
import numpy as np


In [3]:
data = pd.read_excel('iris.xls')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [6]:
x = data.drop('Classification', axis = 1)
y = data['Classification']

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 42, test_size = 0.4)

In [26]:
x_test.head()

SL   SW   PL   PW
73   6.1  2.8  4.7  1.2
18   5.7  3.8  1.7  0.3
118  7.7  2.6  6.9  2.3
78   6.0  2.9  4.5  1.5
76   6.8  2.8  4.8  1.4

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [11]:
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, f1_score
from sklearn.metrics import classification_report
def model_performance(y_true, x_test, model):
  y_pred = model.predict(x_test)
  print(classification_report(y_true, y_pred))
  print('accuracy' , accuracy_score(y_true, y_pred))
  print('precision_score', precision_score(y_true, y_pred, average='micro'))
  print('f1-score', f1_score(y_true,y_pred , average='micro'))
  print('confussion matrix')
  print(confusion_matrix(y_true,y_pred))

In [21]:
x_test.shape

(60, 4)

In [16]:
# MODEL
from sklearn.neighbors import KNeighborsClassifier
K_model = KNeighborsClassifier(n_neighbors=4)
K_model.fit(x_train, y_train)
model_performance(y_test, x_test, K_model)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        23
Iris-versicolor       1.00      1.00      1.00        19
 Iris-virginica       1.00      1.00      1.00        18

       accuracy                           1.00        60
      macro avg       1.00      1.00      1.00        60
   weighted avg       1.00      1.00      1.00        60

accuracy 1.0
precision_score 1.0
f1-score 1.0
confussion matrix
[[23  0  0]
 [ 0 19  0]
 [ 0  0 18]]


In [20]:
#  MODEL CREATED AND SAVING THE MODEL OBJECT
import pickle
with open('model.pkl', 'wb') as fp:
    pickle.dump(K_model, fp)